-- СТВОРЕННЯ ТАБЛИЦІ ФАКУЛЬТЕТИ (FACULTIES)
CREATE TABLE FACULTIES (
    ID SERIAL PRIMARY KEY,
    DEAN VARCHAR(255) NOT NULL CHECK (DEAN <> ''),
    NAME VARCHAR(100) NOT NULL UNIQUE CHECK (NAME <> '')
);

-- ЗАПОВНЕННЯ ТАБЛИЦІ ФАКУЛЬТЕТИ
INSERT INTO FACULTIES (DEAN, NAME) VALUES
('John Smith', 'Faculty of Science'),
('Emma Johnson', 'Faculty of Arts'),
('Olivia Williams', 'Faculty of Engineering'),
('Liam Brown', 'Faculty of Medicine'),
('Noah Jones', 'Faculty of Business'),
('Ava Garcia', 'Faculty of Law'),
('Sophia Martinez', 'Faculty of Education'),
('Isabella Davis', 'Faculty of Social Sciences'),
('Mason Rodriguez', 'Faculty of Humanities'),
('James Martinez', 'Faculty of Natural Sciences'),
('Mia Hernandez', 'Faculty of Computer Science'),
('Charlotte Lopez', 'Faculty of Environmental Studies'),
('Amelia Gonzalez', 'Faculty of Health Sciences'),
('Evelyn Wilson', 'Faculty of Music'),
('Harper Anderson', 'Faculty of Fine Arts'),
('Elijah Thomas', 'Faculty of Political Science'),
('Oliver Taylor', 'Faculty of Economics'),
('Lucas Moore', 'Faculty of Architecture'),
('Henry Jackson', 'Faculty of Chemistry'),
('Alexander Martin', 'Faculty of Physics'),
('Sebastian Lee', 'Faculty of Biology'),
('Jack Perez', 'Faculty of Earth Sciences'),
('Aiden Thompson', 'Faculty of Mathematics'),
('Jackson White', 'Faculty of Philosophy'),
('Levi Harris', 'Faculty of History'),
('Mateo Sanchez', 'Faculty of Sociology'),
('David Clark', 'Faculty of Psychology'),
('Jaxon Ramirez', 'Faculty of Anthropology'),
('Grayson Lewis', 'Faculty of Religious Studies'),
('Carter Robinson', 'Faculty of Film Studies'),
('Wyatt Walker', 'Faculty of Communication'),
('Dylan Young', 'Faculty of International Relations'),
('Luke Allen', 'Faculty of Gender Studies'),
('Gabriel King', 'Faculty of Literature'),
('Michael Wright', 'Faculty of Sports Science'),
('Julian Scott', 'Faculty of Urban Planning'),
('Isaac Torres', 'Faculty of Veterinary Medicine'),
('Jayden Nguyen', 'Faculty of Dentistry'),
('Lincoln Hill', 'Faculty of Nursing'),
('Madison Flores', 'Faculty of Midwifery'),
('Scarlett Green', 'Faculty of Occupational Therapy'),
('Victoria Adams', 'Faculty of Physiotherapy'),
('Aria Nelson', 'Faculty of Dietetics'),
('Grace Baker', 'Faculty of Nutrition'),
('Chloe Hall', 'Faculty of Public Health'),
('Camila Rivera', 'Faculty of Epidemiology'),
('Penelope Campbell', 'Faculty of Biostatistics'),
('Layla Mitchell', 'Faculty of Gerontology'),
('Riley Carter', 'Faculty of Health Policy'),
('Nora Brooks', 'Faculty of Biomedical Engineering');

