-- СТВОРЕННЯ ТАБЛИЦІ ПРЕДМЕТИ (SUBJECTS)
CREATE TABLE SUBJECTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE CHECK (NAME <> '')
);

-- ЗАПОВНЕННЯ ТАБЛИЦІ ПРЕДМЕТИ
INSERT INTO SUBJECTS (NAME) VALUES
('MATHEMATICS'),
('PHYSICS'),
('CHEMISTRY'),
('BIOLOGY'),
('COMPUTER SCIENCE'),
('ECONOMICS'),
('HISTORY'),
('GEOGRAPHY'),
('PHILOSOPHY'),
('SOCIOLOGY'),
('PSYCHOLOGY'),
('LAW'),
('MEDICINE'),
('DENTISTRY'),
('NURSING'),
('PHARMACY'),
('ENGINEERING'),
('ARCHITECTURE'),
('ARTS'),
('MUSIC');
