--SELECT * FROM STUDENTS
--SELECT NAME FROM STUDENTS
--SELECT AVERAGE_SCORE FROM STUDENTS
--SELECT NAME FROM STUDENTS WHERE AVERAGE_SCORE > 3.0
--SELECT DISTINCT COUNTRY FROM STUDENTS
--SELECT DISTINCT CITY FROM STUDENTS
--SELECT DISTINCT GROUP_NAME FROM STUDENTS
SELECT DISTINCT MIN_GRADE_TEACHING FROM STUDENTS;


