-- СТВОРЕННЯ ТАБЛИЦІ СПОНСОРИ (SPONSORS)
CREATE TABLE IF NOT EXIST SPONSORS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE CHECK (NAME <> '')
);

-- ЗАПОВНЕННЯ ТАБЛИЦІ СПОНСОРИ
INSERT INTO SPONSORS (NAME) VALUES
('Sponsor A'),
('Sponsor B'),
('Sponsor C'),
('Sponsor D'),
('Sponsor E'),
('Sponsor F'),
('Sponsor G'),
('Sponsor H'),
('Sponsor I'),
('Sponsor J'),
('Sponsor K'),
('Sponsor L'),
('Sponsor M'),
('Sponsor N'),
('Sponsor O'),
('Sponsor P'),
('Sponsor Q'),
('Sponsor R'),
('Sponsor S'),
('Sponsor T'),
('Sponsor U'),
('Sponsor V'),
('Sponsor W'),
('Sponsor X'),
('Sponsor Y'),
('Sponsor Z'),
('Sponsor AA'),
('Sponsor AB'),
('Sponsor AC'),
('Sponsor AD'),
('Sponsor AE'),
('Sponsor AF'),
('Sponsor AG'),
('Sponsor AH'),
('Sponsor AI'),
('Sponsor AJ'),
('Sponsor AK'),
('Sponsor AL'),
('Sponsor AM'),
('Sponsor AN'),
('Sponsor AO'),
('Sponsor AP'),
('Sponsor AQ'),
('Sponsor AR'),
('Sponsor AS'),
('Sponsor AT'),
('Sponsor AU'),
('Sponsor AV'),
('Sponsor AW');


