-- ВИВЕСТИ СЬОГОДНІШНЮ ДАТУ
-- SELECT CURRENT_DATE


-- ВИВЕСТИ ВІК НА ОСНОВІ ДАТИ НАРОБЖЕННЯ
-- SELECT EXTRACT(YEAR FROM CURRENT_DATE - DATE_OF_BIRTH)
-- FROM STUDENT

SELECT EXTRACT(YEAR FROM AGE(DATE_OF_BIRTH)) AS AGE_CALCULATED
FROM STUDENT

-- DATE
-- TIME
-- DATETIME
-- TIMESTAMP
-- INTERVAL