-- добавити новий стовпчик разом з значеннями
ALTER TABLE STUDENT
ADD COLUMN DATE_OF_BIRTH DATE;

UPDATE STUDENT
SET DATE_OF_BIRTH = '2000-03-24';

-- добавити новий стовпчик разом з різними значеннями
ALTER TABLE STUDENT
ADD COLUMN JOB VARCHAR(20);

UPDATE STUDENT
SET JOB = 'TEACHER'
WHERE AGE <= 26;

UPDATE STUDENT
SET JOB = 'WORKER'
WHERE AGE > 26;

UPDATE STUDENT
SET JOB = 'PROGRAMMER'
WHERE FIRST_NAME = 'Mia' AND LAST_NAME = 'Baker';